### ISSUE TITLE
hsf-pandora-boot-provider 启动报错

### ISSUE THREAD

**Issue by heyibo8888** [aliyun/alibabacloud-microservice-demo#4]
20-01-13 23:41:25.822  WARN 24396 --- [           main] ConfigServletWebServerApplicationContext : Exception encountered during context initialization - cancelling refresh attempt: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'helloServiceImpl#HSFProvider': Invocation of init method failed; nested exception is java.lang.RuntimeException: java.lang.RuntimeException: java.util.concurrent.ExecutionException: java.lang.RuntimeException: java.lang.NullPointerException
2020-01-13 23:41:25.826  INFO 24396 --- [           main] o.apache.catalina.core.StandardService   : Stopping service [Tomcat]
2020-01-13 23:41:25.847  INFO 24396 --- [           main] ConditionEvaluationReportLoggingListener : 

Error starting ApplicationContext. To display the conditions report re-run your application with 'debug' enabled.
2020-01-13 23:41:25.856 ERROR 24396 --- [           main] o.s.boot.SpringApplication               : Application run failed

org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'helloServiceImpl#HSFProvider': Invocation of init method failed; nested exception is java.lang.RuntimeException: java.lang.RuntimeException: java.util.concurrent.ExecutionException: java.lang.RuntimeException: java.lang.NullPointerException
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1778) ~[spring-beans-5.1.8.RELEASE.jar!/:5.1.8.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:593) ~[spring-beans-5.1.8.RELEASE.jar!/:5.1.8.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:515) ~[spring-beans-5.1.8.RELEASE.jar!/:5.1.8.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:320) ~[spring-beans-5.1.8.RELEASE.jar!/:5.1.8.RELEASE]
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:222) ~[spring-beans-5.1.8.RELEASE.jar!/:5.1.8.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:318) ~[spring-beans-5.1.8.RELEASE.jar!/:5.1.8.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:199) ~[spring-beans-5.1.8.RELEASE.jar!/:5.1.8.RELEASE]
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:845) ~[spring-beans-5.1.8.RELEASE.jar!/:5.1.8.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:877) ~[spring-context-5.1.8.RELEASE.jar!/:5.1.8.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:549) ~[spring-context-5.1.8.RELEASE.jar!/:5.1.8.RELEASE]
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:140) ~[spring-boot-2.1.6.RELEASE.jar!/:2.1.6.RELEASE]
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:742) [spring-boot-2.1.6.RELEASE.jar!/:2.1.6.RELEASE]
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:389) [spring-boot-2.1.6.RELEASE.jar!/:2.1.6.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:311) [spring-boot-2.1.6.RELEASE.jar!/:2.1.6.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1213) [spring-boot-2.1.6.RELEASE.jar!/:2.1.6.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1202) [spring-boot-2.1.6.RELEASE.jar!/:2.1.6.RELEASE]
	at com.alibaba.edas.HSFProviderApplication.main(HSFProviderApplication.java:14) [classes!/:na]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_152]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_152]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_152]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_152]
	at com.taobao.pandora.boot.loader.MainMethodRunner.run(MainMethodRunner.java:54) [hsf-pandora-boot-provider-1.0.jar:na]
	at com.taobao.pandora.boot.loader.Launcher.launch(Launcher.java:87) [hsf-pandora-boot-provider-1.0.jar:na]
	at com.taobao.pandora.boot.loader.Launcher.launch(Launcher.java:50) [hsf-pandora-boot-provider-1.0.jar:na]
	at com.taobao.pandora.boot.loader.SarLauncher.main(SarLauncher.java:171) [hsf-pandora-boot-provider-1.0.jar:na]
Caused by: java.lang.RuntimeException: java.lang.RuntimeException: java.util.concurrent.ExecutionException: java.lang.RuntimeException: java.lang.NullPointerException
	at com.taobao.hsf.app.api.util.HSFApiProviderBean.publish(HSFApiProviderBean.java:552) ~[hsf-app-api-2.2.8.2.jar!/:na]
	at com.taobao.hsf.app.spring.util.HSFSpringProviderBean.doPublish(HSFSpringProviderBean.java:83) ~[hsf-app-spring-2.2.8.2.jar!/:na]
	at com.taobao.hsf.app.spring.util.HSFSpringProviderBean.init(HSFSpringProviderBean.java:77) ~[hsf-app-spring-2.2.8.2.jar!/:na]
	at com.taobao.hsf.app.spring.util.HSFSpringProviderBean.afterPropertiesSet(HSFSpringProviderBean.java:65) ~[hsf-app-spring-2.2.8.2.jar!/:na]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeInitMethods(AbstractAutowireCapableBeanFactory.java:1837) ~[spring-beans-5.1.8.RELEASE.jar!/:5.1.8.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1774) ~[spring-beans-5.1.8.RELEASE.jar!/:5.1.8.RELEASE]
	... 24 common frames omitted
Caused by: java.lang.RuntimeException: java.util.concurrent.ExecutionException: java.lang.RuntimeException: java.lang.NullPointerException
	at com.taobao.hsf.model.metadata.ServiceMetadata.exportSync(ServiceMetadata.java:376) ~[hsf-core-2.2.8.2.jar!/:na]
	at com.taobao.hsf.app.api.util.HSFApiProviderBean.publish(HSFApiProviderBean.java:550) ~[hsf-app-api-2.2.8.2.jar!/:na]
	... 29 common frames omitted
Caused by: java.util.concurrent.ExecutionException: java.lang.RuntimeException: java.lang.NullPointerException
	at java.util.concurrent.FutureTask.report(FutureTask.java:122) ~[na:1.8.0_152]
	at java.util.concurrent.FutureTask.get(FutureTask.java:192) ~[na:1.8.0_152]
	at com.taobao.hsf.threadpool.impl.SingleThreadScheduledExecutor$RunnableScheduleFutureDecorator.get(SingleThreadScheduledExecutor.java:184) ~[hsf-core-2.2.8.2.jar!/:na]
	at com.taobao.hsf.model.metadata.ServiceMetadata.exportSync(ServiceMetadata.java:366) ~[hsf-core-2.2.8.2.jar!/:na]
	... 30 common frames omitted
Caused by: java.lang.RuntimeException: java.lang.NullPointerException
	at com.taobao.hsf.model.metadata.ServiceMetadata.export(ServiceMetadata.java:340) ~[hsf-core-2.2.8.2.jar!/:na]
	at com.taobao.hsf.model.metadata.ServiceMetadata$1.call(ServiceMetadata.java:361) ~[hsf-core-2.2.8.2.jar!/:na]
	at com.taobao.hsf.model.metadata.ServiceMetadata$1.call(ServiceMetadata.java:358) ~[hsf-core-2.2.8.2.jar!/:na]
	at java.util.concurrent.FutureTask.run$$$capture(FutureTask.java:266) ~[na:1.8.0_152]
	at java.util.concurrent.FutureTask.run(FutureTask.java) ~[na:1.8.0_152]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180) ~[na:1.8.0_152]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293) ~[na:1.8.0_152]
	at com.taobao.hsf.threadpool.impl.SingleThreadScheduledExecutor$RunnableScheduleFutureDecorator.run(SingleThreadScheduledExecutor.java:155) ~[hsf-core-2.2.8.2.jar!/:na]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) ~[na:1.8.0_152]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) ~[na:1.8.0_152]
	at java.lang.Thread.run(Thread.java:748) ~[na:1.8.0_152]
Caused by: java.lang.NullPointerException: null
	at com.taobao.hsf.unit.service.impl.UnitProtocolInterceptor.export(UnitProtocolInterceptor.java:28) ~[hsf-feature-unit-2.2.8.2.jar!/:na]
	at com.taobao.hsf.protocol.AbstractDelegateProtocolInterceptor.export(AbstractDelegateProtocolInterceptor.java:26) ~[hsf-core-2.2.8.2.jar!/:na]
	at com.taobao.hsf.region.service.impl.RegionProtocolInterceptor.export(RegionProtocolInterceptor.java:33) ~[hsf-feature-region-2.2.8.2.jar!/:na]
	at com.taobao.hsf.plugins.eagleeye.protocol.EagleEyeProtocolInterceptor.export(EagleEyeProtocolInterceptor.java:37) ~[hsf-feature-eagleeye-2.2.8.2.jar!/:na]
	at com.taobao.hsf.process.component.CodeployProtocolInterceptor.export(CodeployProtocolInterceptor.java:31) ~[hsf-feature-codeploy-2.2.8.2.jar!/:na]
	at com.taobao.hsf.feature.optimized.hessian.protocolinterceptor.OptimizedHessianProtocolInterceptor.export(OptimizedHessianProtocolInterceptor.java:29) ~[hsf-feature-optimized-hessian-2.2.8.2.jar!/:na]
	at com.taobao.hsf.protocol.AbstractDelegateProtocolInterceptor.export(AbstractDelegateProtocolInterceptor.java:26) ~[hsf-core-2.2.8.2.jar!/:na]
	at com.taobao.hsf.plugins.spas.SpasProtocolInterceptor.export(SpasProtocolInterceptor.java:21) ~[hsf-feature-spas-2.2.8.2.jar!/:na]
	at com.taobao.hsf.protocol.DelayPublishProtocolInterceptor.export(DelayPublishProtocolInterceptor.java:26) ~[hsf-feature-default-2.2.8.2.jar!/:na]
	at com.taobao.hsf.metadata.store.MetadataReportProtocolInterceptor.export(MetadataReportProtocolInterceptor.java:46) ~[hsf-feature-metadata-report-2.2.8.2.jar!/:na]
	at com.taobao.hsf.model.metadata.ServiceMetadata.export(ServiceMetadata.java:335) ~[hsf-core-2.2.8.2.jar!/:na]
	... 10 common frames omitted

Stopping available components

**Comment by heyibo8888** [comment]
@JacksonTian @tdy218 @ralf0131 @fangjian0423
运行时配置了vm参数 
-Djmenv.tbsite.net=192.168.157.1 -Dpandora.location=E:/server/.m2/repository/com/taobao/pandora/taobao-hsf.sar/2019-06-stable/taobao-hsf.sar-2019-06-stable.jar

**Comment by lichong2** [comment]
我也遇到同样的问题，从git上拉下来的项目启动就报这样的错误！！请问你解决了么

**Comment by heyibo8888** [comment]
没用这个了



---原始邮件---
发件人: "lichong"<notifications@github.com&gt;
发送时间: 2020年3月11日(周三) 下午4:12
收件人: "aliyun/alibabacloud-microservice-demo"<alibabacloud-microservice-demo@noreply.github.com&gt;;
抄送: "Author"<author@noreply.github.com&gt;;"heyibo8888"<heyb@qq.com&gt;;
主题: Re: [aliyun/alibabacloud-microservice-demo] hsf-pandora-boot-provider 启动报错 (#4)



我也遇到同样的问题，从git上拉下来的项目启动就报这样的错误！！请问你解决了么

**Comment by bottomheater** [comment]
我加了 hsf.server.ip 可以运行了
vm参数如下
-Djmenv.tbsite.net=127.0.0.1
-Dpandora.location=D:/env/maven/repository/com/taobao/pandora/taobao-hsf.sar/2019-06-stable/taobao-hsf.sar-2019-06-stable.jar
-Dhsf.server.ip=127.0.0.1

**Comment by bottomheater** [comment]
hsf-pandora-boot-provider和hsf-pandora-boot-consumer都要添加vm参数，才能互通
vm参数如下
-Djmenv.tbsite.net=127.0.0.1
-Dhsf.server.ip=127.0.0.1

**Comment by 2425691371** [comment]
> hsf-pandora-boot-provider和hsf-pandora-boot-consumer都要添加vm参数，才能互通 vm参数如下 -Djmenv.tbsite.net=127.0.0.1 -Dhsf.server.ip=127.0.0.1

大佬，这个vm参数在哪设置呀，望不吝赐教

**Comment by 2425691371** [comment]
> hsf-pandora-boot-provider和hsf-pandora-boot-consumer都要添加vm参数，才能互通 vm参数如下 -Djmenv.tbsite.net=127.0.0.1 -Dhsf.server.ip=127.0.0.1

@bottomheater 大佬，这个vm参数在哪设置呀，望指教一二

**Comment by lichong2** [comment]
> > hsf-pandora-boot-provider和hsf-pandora-boot-consumer都要添加vm参数，才能互通 vm参数如下 -Djmenv.tbsite.net=127.0.0.1 -Dhsf.server.ip=127.0.0.1
> 
> @bottomheater 大佬，这个vm参数在哪设置呀，望指教一二


ide中启动配置：
在 VM options 中配置参数-Dhsf.server.ip=${IP} -Dhsf.server.port=12301

生成jar时启动：
java -Djmenv.tbsite.net=127.0.0.1 -Daddress.server.ip=172.19.2.63 -Dhsf.server.port=12301 -Dpandora.location=/home/runtime/test/taobao-hsf.sar-2019-06-stable.jar -jar athena.jar --server.port=1812 > nohup.out

参数说明：
官网说明地址：https://help.aliyun.com/document_detail/140491.html?spm=5176.11065259.1996646101.searchclickresult.444782b2IlS22X

-Djmenv.tbsite.net：注册中心的地址。 -Daddress.server.ip： 指定需要绑定的 IP 地址。在多网卡情况下默认绑定第一个网卡，通过该参数指定需要绑定的 IP（即部署机器的ip地址）。 -Dhsf.server.port： 指定 HSF 的启动服务绑定端口，默认为 12200。如果在本地启动多个 HSF Provider，则需要修改此端口。 -Dpandora.location: 指定的路径必须是全路径，使用命令行启动时，必须显示指定 taobao-hsf.sar 的位置。 --server.port=1812 ： 应用指定启动端口，可以在配置文件中配置。这里可以不需要配置。 2,3当机器中只有一个项目部署时可以不用指定，但是当多个项目同时部署时，启动时会出现HSF-0016的错误码时，可以修改3解决。

单元测试：
单元测试时会出现上述的报错，配置以下信息到pom文件。
<plugin> <groupId>org.apache.maven.plugins</groupId> <artifactId>maven-surefire-plugin</artifactId> <configuration> <argLine>-Dhsf.server.ip=127.0.0.1</argLine> </configuration> </plugin>
